# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cart_item_dto import CartItemDto  # noqa: E501
from swagger_client.rest import ApiException


class TestCartItemDto(unittest.TestCase):
    """CartItemDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCartItemDto(self):
        """Test CartItemDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cart_item_dto.CartItemDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
