# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.main_controller_api import MainControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMainControllerApi(unittest.TestCase):
    """MainControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.main_controller_api.MainControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_item_to_cart_using_put(self):
        """Test case for add_item_to_cart_using_put

        addItemToCart  # noqa: E501
        """
        pass

    def test_add_item_using_post(self):
        """Test case for add_item_using_post

        addItem  # noqa: E501
        """
        pass

    def test_del_item_from_cart_using_delete(self):
        """Test case for del_item_from_cart_using_delete

        delItemFromCart  # noqa: E501
        """
        pass

    def test_del_item_using_delete(self):
        """Test case for del_item_using_delete

        delItem  # noqa: E501
        """
        pass

    def test_get_cart_using_get(self):
        """Test case for get_cart_using_get

        getCart  # noqa: E501
        """
        pass

    def test_get_item_using_get(self):
        """Test case for get_item_using_get

        getItem  # noqa: E501
        """
        pass

    def test_get_items_using_get(self):
        """Test case for get_items_using_get

        getItems  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
