# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class CartItemDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'item_id': 'str',
        'user_id': 'str'
    }

    attribute_map = {
        'id': 'id',
        'item_id': 'item_id',
        'user_id': 'user_id'
    }

    def __init__(self, id=None, item_id=None, user_id=None, _configuration=None):  # noqa: E501
        """CartItemDto - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._item_id = None
        self._user_id = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if item_id is not None:
            self.item_id = item_id
        if user_id is not None:
            self.user_id = user_id

    @property
    def id(self):
        """Gets the id of this CartItemDto.  # noqa: E501


        :return: The id of this CartItemDto.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CartItemDto.


        :param id: The id of this CartItemDto.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def item_id(self):
        """Gets the item_id of this CartItemDto.  # noqa: E501


        :return: The item_id of this CartItemDto.  # noqa: E501
        :rtype: str
        """
        return self._item_id

    @item_id.setter
    def item_id(self, item_id):
        """Sets the item_id of this CartItemDto.


        :param item_id: The item_id of this CartItemDto.  # noqa: E501
        :type: str
        """

        self._item_id = item_id

    @property
    def user_id(self):
        """Gets the user_id of this CartItemDto.  # noqa: E501


        :return: The user_id of this CartItemDto.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this CartItemDto.


        :param user_id: The user_id of this CartItemDto.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CartItemDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CartItemDto):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CartItemDto):
            return True

        return self.to_dict() != other.to_dict()
